Alpha autoupdater
Krypton-Suite/Extended-Toolkit pull request #425
Opened 2023-06-21 07:31 UTC by Wagnerp

* Closes #405 & #414

2023-06-22 07:38 UTC, Smurf-IV requested changes

2023-06-22 07:38 UTC, Smurf-IV commented on Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Software.Updater/Auto Updater/UX/DownloadUpdateDialog.cs
> +﻿using System;
New file needs the license agreement

2023-06-22 15:45 UTC, Wagnerp commented on Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Software.Updater/Auto Updater/UX/DownloadUpdateDialog.cs
> +﻿using System;
Done :)

2023-06-23 06:40 UTC, Smurf-IV commented on Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Software.Updater/Auto Updater/Translations/AutoUpdaterStrings.cs
> + * Copyright (c) 2017 - 2023 Krypton Suite
Wrong start date for new files

2023-06-23 07:02 UTC, Wagnerp commented on Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Software.Updater/Auto Updater/Translations/AutoUpdaterStrings.cs
> + * Copyright (c) 2017 - 2023 Krypton Suite
Fixed

2023-06-25 07:20 UTC, merged